---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: true
configure_osx: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - 'App Store'
  - Calendar
  - Mail
  - Contacts
  - Pages
  - Keynote
  - Numbers
  - Photos
  - iMovie
  - Maps
  - FaceTime
  - Reminders
  - Notes
  - Music
  - Podcasts
  - News
  - 'System Preferences'
dockitems_persist:
  - name: Superhuman
    path: "/Applications/Superhuman.app/"
    pos: 1
  - name: Safari
    path: "/Applications/Safari.app/"
    pos: 2
  - name: Fantastical
    path: "/Applications/Fantastical.app/"
    pos: 3
  - name: iTerm
    path: "/Applications/iTerm.app/"
    pos: 4
  - name: Slack
    path: "/Applications/Slack.app/"
    pos: 5
  - name: Messages
    path: "/Applications/Messages.app/"
    pos: 6

configure_sudoers: true
sudoers_custom_config: '%admin ALL=(ALL) NOPASSWD: ALL'

homebrew_taps:
  - shopify/shopify
  - ArmMbed/homebrew-formulae

homebrew_installed_packages:
  - brew-cask-completion
  - nvim
  - ripgrep  # for nvim
  - fd  # for nvim
  - 1password-cli
  - prettierd
  - tmux
  - pdm  # have both python package managers just in case
  - uv  # have both python package managers just in case
  - mosh
  - awscli
  - go
  - node
  - ruby  # required for gems to work correctly
  - svn   # required for fonts to work correctly
  - ccls
  - yarn
  - ag
  - tree
  - opam
  - vim
  - lsd  # exa no longer maintained
  - antidote  # antibody no longer maintained
  - zsh
  - zsh-completions
  - tcl-tk
  - libgit2
  - ffmpeg
  - themekit
  - geckodriver
  - pandoc
  - gpg
  - mas
  - ispell
  - arm-none-eabi-gcc

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # sudo required
  - temurin@17  # new, for newer Android
  - xquartz
  # fonts
  - font-source-code-pro
  - font-montserrat
  - font-roboto
  - font-roboto-mono
  - font-hack-nerd-font
  # core apps
  - alfred
  - box-drive
  - vlc
  - fantastical
  - google-chrome
  - firefox
  - 1password
  - rectangle
  - hammerspoon
  - devonthink
  - slack
  - the-unarchiver
  - bartender
  - transmission
  - veracrypt
  - steam
  - jdownloader
  - imageoptim
  - handbrake
  - darktable
  - name-mangler
  - bambu-studio
  - microsoft-office
  - jump
  - jump-desktop-connect
  # dev
  - emacs
  - docker
  - android-studio
  - iterm2
  - dash
  - coolterm
  - r
  - rstudio
  - mactex
  - miniforge

mas_installed_apps:
  - { id: 497799835, name: "XCode" }
  - { id: 1435957248, name: "Drafts" }
  - { id: 1225570693, name: "Ulysses" }
  - { id: 1451685025, name: "WireGuard" }
  - { id: 1447330651, name: "Copilot" }
mas_email: ""
mas_password: ""

gem_packages:
  - cocoapods

npm_packages:
  - prettier
  - eslint
  - typescript
  - @typescript-eslint/parser
  - @typescript-eslint/eslint-plugin

configure_sublime: false
